"""Search contracts: facts, crawlable routes, language pairs and discovery files."""
import json,sys,unittest
from pathlib import Path
from lxml import html,etree
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'scripts'))
from seo import PAGES,BASE

class SearchContracts(unittest.TestCase):
    def test_metadata_language_pairs_and_crawlable_links(self):
        titles=set()
        for kind,page in PAGES.items():
            for lang in ['en','es']:
                path=page[lang];doc=html.parse(str(ROOT/path.strip('/')/'index.html'))
                title=doc.xpath('string(//title)');self.assertNotIn(title,titles);titles.add(title)
                self.assertEqual(doc.xpath('//link[@rel="canonical"]/@href'),[BASE+path])
                alts={el.get('hreflang'):el.get('href') for el in doc.xpath('//link[@hreflang]')}
                self.assertEqual(alts,{'en':BASE+page['en'],'es':BASE+page['es'],'x-default':BASE+page['en']})
                robots=doc.xpath('string(//meta[@name="robots"]/@content)')
                self.assertEqual('noindex' in robots,kind=='privacy')
                self.assertTrue(doc.xpath('//meta[@property="og:image:alt"]/@content'))
                self.assertTrue(doc.xpath('//meta[@name="twitter:image"]/@content'))
                self.assertFalse(doc.xpath('//a[not(@href)]'),path)
                self.assertFalse(doc.xpath('//link[contains(@href,"fonts.googleapis.com")]'))
                self.assertEqual(doc.xpath('//link[@rel="stylesheet"]/@href'),['/assets/site.min.css'])
                if kind=='home':
                    preload=doc.xpath('//link[@rel="preload" and @as="image"]')[0]
                    source=doc.xpath('//div[@data-hero-frame="day"]//source')[0]
                    self.assertEqual(preload.get('imagesrcset'),source.get('srcset'))
                    self.assertEqual(preload.get('imagesizes'),source.get('sizes'))
                    for image in doc.xpath('//source[@type="image/avif"]/@srcset'):
                        for variant in image.split(','):
                            self.assertTrue((ROOT/variant.strip().split()[0].lstrip('/')).exists())

    def test_structured_facts_and_visible_breadcrumbs(self):
        for kind,page in PAGES.items():
            for lang in ['en','es']:
                path=page[lang];doc=html.parse(str(ROOT/path.strip('/')/'index.html'))
                data=json.loads(doc.xpath('string(//script[@type="application/ld+json"])'))
                bytype={node['@type']:node for node in data['@graph']}
                villa=bytype['LodgingBusiness'];self.assertEqual(villa['@id'],BASE+'/#villa')
                self.assertEqual(villa['containsPlace']['numberOfBedrooms'],4)
                self.assertEqual(villa['containsPlace']['numberOfBathroomsTotal'],3.5)
                self.assertEqual(villa['telephone'],'+50370528003')
                # Imported capacity is unresolved; prices, eligibility and ratings must not be invented.
                for key in ['aggregateRating','occupancy','offers','geo','priceRange','starRating']:
                    self.assertNotIn('"'+key+'"',json.dumps(data))
                if kind!='home':
                    crumbs=bytype['BreadcrumbList']['itemListElement']
                    self.assertEqual(crumbs[-1]['item'],BASE+path)
                    self.assertEqual(doc.xpath('string(//nav[@class="page-breadcrumbs"]//*[@aria-current="page"])'),crumbs[-1]['name'])
                if kind=='gallery':self.assertEqual(len(bytype['ImageGallery']['associatedMedia']),35)

    def test_sitemap_images_and_indexable_pages(self):
        ns={'s':'http://www.sitemaps.org/schemas/sitemap/0.9','im':'http://www.google.com/schemas/sitemap-image/1.1'}
        tree=etree.parse(str(ROOT/'sitemap.xml'))
        expected={BASE+page[lang] for page in PAGES.values() if page.get('index',True) for lang in ['en','es']}
        self.assertEqual(set(tree.xpath('//s:url/s:loc/text()',namespaces=ns)),expected)
        for image in tree.xpath('//im:loc/text()',namespaces=ns):
            self.assertTrue(image.startswith(BASE+'/assets/'))
            self.assertTrue((ROOT/image.removeprefix(BASE+'/')).exists())
            self.assertNotIn('2569999123',image)
        robots=(ROOT/'robots.txt').read_text();self.assertIn('Sitemap: '+BASE+'/sitemap.xml',robots)
        self.assertNotIn('Disallow: /assets/',robots)
        self.assertTrue(tree.xpath('//s:lastmod',namespaces=ns))

    def test_error_page_and_reproducible_styles(self):
        from rcssmin import cssmin
        from build_assets import SOURCES
        expected='/* Generated by scripts/build_assets.py; edit source stylesheets. */\n'+cssmin('\n'.join((ROOT/'assets'/name).read_text() for name in SOURCES))+'\n'
        self.assertEqual((ROOT/'assets/site.min.css').read_text(),expected)
        doc=html.parse(str(ROOT/'404.html'))
        self.assertIn('noindex',doc.xpath('string(//meta[@name="robots"]/@content)'))
        self.assertEqual(len(doc.xpath('//h1')),1)
        self.assertTrue(doc.xpath('//a[@href="/"]'));self.assertTrue(doc.xpath('//a[@href="/es/"]'))
