"""Combine/minify CSS in cascade order; committed output needs no runtime tooling."""
from pathlib import Path
from rcssmin import cssmin
ROOT=Path(__file__).resolve().parents[1]
SOURCES=['fonts.css','site.css','editorial.css','retreat.css','guide.css','hospitality.css']
def build_css():
    css='\n'.join((ROOT/'assets'/name).read_text() for name in SOURCES)
    (ROOT/'assets/site.min.css').write_text('/* Generated by scripts/build_assets.py; edit source stylesheets. */\n'+cssmin(css)+'\n')
