"""Editorial public pages. Shared renderer keeps English and Spanish in step."""
from html import escape
import json
from pathlib import Path
from PIL import Image
ROOT = Path(__file__).resolve().parents[1]
CATALOG = json.loads((ROOT / 'content/listing-photos.json').read_text())
PHOTOS = CATALOG['photos']
AIRBNB = 'https://www.airbnb.com/rooms/47911834'

def photo(index, lang, hero=False, sizes='(max-width: 700px) 100vw, 50vw'):
    p = PHOTOS[index]
    sources = {}
    for size in [480,960,1600,1920]:
        path = f"/assets/listing/{p['id']}-{size}.webp"
        with Image.open(ROOT / path.lstrip('/')) as im:
            sources.setdefault(im.width, path)
            w,h = im.size
    srcset = ', '.join(f'{url} {width}w' for width,url in sources.items())
    load = 'fetchpriority="high"' if hero else 'loading="lazy"'
    return f'<img src="/assets/listing/{p["id"]}-960.webp" srcset="{srcset}" sizes="{sizes}" width="{w}" height="{h}" alt="{escape(p["alt"][lang])}" {load} decoding="async">'

def navigation(lang, active='home'):
    T=lambda en,es:es if lang=='es' else en
    home='/es/' if lang=='es' else '/'
    gallery='/es/fotos/' if lang=='es' else '/photos/'
    guide='/es/guia/' if lang=='es' else '/guide/'
    other=('/photos/' if lang=='es' else '/es/fotos/') if active=='photos' else ('/' if lang=='es' else '/es/')
    return f'''<a class="skip" href="#main">{T('Skip to content','Ir al contenido')}</a>
<header class="site-header editorial-header">
 <a class="brand wordmark" href="{home}" aria-label="White Swan — {T('home','inicio')}"><img src="/assets/favicon.svg" width="30" height="30" alt="">WHITE SWAN<small>XANADU, EL SALVADOR</small></a>
 <nav aria-label="{T('Main navigation','Navegación principal')}"><a href="{home}#villa">{T('The villa','La villa')}</a><a href="{gallery}">{T('The spaces','Los espacios')}</a><a href="{home}#services">{T('Experiences','Experiencias')}</a><a href="{home}#explore">{T('The coast','La costa')}</a></nav>
 <div class="header-actions"><a class="language" href="{other}" aria-label="{T('Ver en español','View in English')}" lang="{T('es','en')}">{T('EN <span>/ ES</span>','ES <span>/ EN</span>')}</a><a class="button small" href="{AIRBNB}" target="_blank" rel="noopener" data-placement="navigation">{T('Find your dates','Elige tus fechas')} <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu" aria-label="{T('Open menu','Abrir menú')}"><span></span><span></span></button></div>
</header><nav id="mobile-menu" class="mobile-menu" aria-label="{T('Mobile navigation','Navegación móvil')}" hidden><a href="{home}#villa">{T('The villa','La villa')}</a><a href="{gallery}">{T('Photo tour','Recorrido fotográfico')}</a><a href="{home}#services">{T('Experiences','Experiencias')}</a><a href="{guide}">{T('Guest guide','Guía del huésped')}</a><a href="{AIRBNB}" target="_blank" rel="noopener">{T('Availability on Airbnb','Disponibilidad en Airbnb')} ↗</a></nav>'''

def footer(lang):
    T=lambda en,es:es if lang=='es' else en
    home='/es/' if lang=='es' else '/';guide='/es/guia/' if lang=='es' else '/guide/';privacy='/es/privacidad/' if lang=='es' else '/privacy/'
    return f'''<footer class="site-footer editorial-footer"><div><a class="brand wordmark" href="{home}">WHITE SWAN<small>XANADU, EL SALVADOR</small></a><p>{T('A private place above the Pacific.','Un lugar privado sobre el Pacífico.')}<br>Tamanique · La Libertad</p></div><div><span class="eyebrow">{T('MAKE YOURSELF AT HOME','SIÉNTETE EN CASA')}</span><a href="{guide}">{T('Guest guide','Guía del huésped')}</a><a href="{AIRBNB}" target="_blank" rel="noopener" data-placement="footer">Airbnb ↗</a><a href="https://wa.me/50370528003" target="_blank" rel="noopener" data-placement="footer">WhatsApp ↗</a></div><div><span class="eyebrow">{T('A LITTLE HOUSEKEEPING','ALGUNOS DETALLES')}</span><a href="{privacy}">{T('Privacy & cookies','Privacidad y cookies')}</a><button data-cookie-settings>{T('Cookie preferences','Preferencias de cookies')}</button><span>{T('We speak English & Spanish.','Hablamos español e inglés.')}</span></div><div class="footer-bottom"><span>© {2026} White Swan Villa</span><span>{T('Ocean air. Good company. Nothing rushed.','Brisa del mar. Buena compañía. Sin prisa.')}</span><a href="#top">{T('Back to top','Volver arriba')} ↑</a></div></footer><div class="mobile-bar"><span>WHITE SWAN<small>{T('Your place by the Pacific','Tu lugar junto al Pacífico')}</small></span><a class="button small" href="{AIRBNB}" target="_blank" rel="noopener" data-placement="sticky">{T('Find your dates','Elige tus fechas')} ↗</a></div>'''

def home(lang, head, image, components):
    T=lambda en,es:es if lang=='es' else en
    home='/es/' if lang=='es' else '/';guide='/es/guia/' if lang=='es' else '/guide/';gallery='/es/fotos/' if lang=='es' else '/photos/'
    s=head(lang,home,T('White Swan | A private ocean-view villa in Xanadu, El Salvador','White Swan | Villa privada con vista al mar en Xanadu, El Salvador'),T('Make the Pacific your backdrop. Four bedrooms, a private infinity pool and space to slow down at White Swan Villa in Xanadu, El Salvador.','El Pacífico como escenario. Cuatro habitaciones, piscina infinita privada y espacio para disfrutar sin prisa en White Swan, Xanadu, El Salvador.'),'/' if lang=='es' else '/es/')
    s+=f'''<body class="editorial" id="top">{navigation(lang)}<main id="main">
<section class="hero coast-hero"><div class="hero-photo">{photo(29,lang,True,'100vw')}</div><div class="hero-copy"><span class="eyebrow">{T('YOUR OWN CORNER OF THE PACIFIC','TU PROPIO RINCÓN DEL PACÍFICO')}</span><h1>{T('Stay a little<br><em>closer to paradise.</em>','Quédate un poco<br><em>más cerca del paraíso.</em>')}</h1><p>{T('A private villa. An endless ocean.<br>And all the time in the world to enjoy it.','Una villa privada. Un mar infinito.<br>Y todo el tiempo para disfrutarlo.')}</p><div class="actions"><a class="button light" href="{AIRBNB}" target="_blank" rel="noopener" data-placement="hero">{T('Discover your next escape','Encuentra tu próxima escapada')} ↗</a><a class="hero-link" href="{gallery}">{T('Take a look around','Descubre cada rincón')} <span>→</span></a></div></div><div class="hero-caption"><span>XANADU · EL SALVADOR</span><a href="#villa">{T('SLOW DOWN. SCROLL A LITTLE.','SIN PRISA. SIGUE EXPLORANDO.')} ↓</a><a class="photo-count" href="{gallery}"><span aria-hidden="true">▧</span> {T('36 photos','36 fotos')}</a></div></section>
<div class="stay-facts"><div><strong>04</strong><span>{T('Bedrooms','Habitaciones')}</span></div><div><strong>05</strong><span>{T('Beds','Camas')}</span></div><div><strong>3.5</strong><span>{T('Bathrooms','Baños')}</span></div><div><strong>∞</strong><span>{T('Private pool. Ocean views.','Piscina privada. Vista al mar.')}</span></div><a href="{AIRBNB}" target="_blank" rel="noopener" data-placement="facts">{T('Entire villa, just for you','Toda la villa, solo para ustedes')} <span>↗</span></a></div>
<section class="section villa villa-story" id="villa"><div class="intro"><span class="eyebrow">01 — {T('THIS IS WHITE SWAN','ESTO ES WHITE SWAN')}</span><h2>{T('Some places make<br>you feel <em>different.</em>','Hay lugares que<br>se sienten <em>diferentes.</em>')}</h2><p class="lead-copy">{T('The first swim before breakfast. The ocean from your pillow. A long lunch that somehow becomes sunset.','El primer chapuzón antes del desayuno. El mar desde tu almohada. Un almuerzo largo que, sin darte cuenta, se convierte en atardecer.')}</p><p class="muted">{T('Welcome to your own place above the Pacific. Set in the coastal community of Xanadu, White Swan brings your favourite people together — with room to spread out, settle in and simply be.','Bienvenidos a su lugar sobre el Pacífico. En la comunidad costera de Xanadu, White Swan reúne a tus personas favoritas, con espacio para compartir, descansar y disfrutar a su manera.')}</p><a class="text-link" href="{gallery}">{T('Step inside the villa','Entra a la villa')} <span>↗</span></a><div class="story-note"><span class="small-sun" aria-hidden="true">✳</span><p>{T('A whole home.<br>A slower kind of day.','Una casa entera.<br>Un día con otro ritmo.')}</p></div></div><div class="story-photos"><a href="{gallery}#outdoors" class="story-main">{photo(28,lang)}</a><a href="{gallery}#living" class="story-inset">{photo(1,lang)}</a><span class="vertical-note">WHITE SWAN / {T('LIFE AT YOUR PACE','LA VIDA A TU RITMO')}</span></div></section>
<section class="section space-section" id="spaces"><div class="section-heading"><div><span class="eyebrow">02 — {T('ROOM TO MAKE MEMORIES','ESPACIO PARA CREAR RECUERDOS')}</span><h2>{T('Come together.<br><em>Find your own quiet.</em>','Compartan momentos.<br><em>Encuentren su calma.</em>')}</h2></div><div><p>{T('Four bedrooms upstairs. Open living below. And the Pacific, never far from view.','Cuatro habitaciones arriba. Espacios abiertos abajo. Y el Pacífico, siempre cerca.')}</p><a class="text-link" href="{gallery}">{T('Explore all 36 photos','Explora las 36 fotos')} ↗</a></div></div><div class="space-grid">'''
    for i,number,title,copy in [(8,'01',T('Wake up to the Pacific','Despierta frente al Pacífico'),T('The primary bedroom · ocean views','La habitación principal · vista al mar')),(14,'02',T('Room for your people','Espacio para los tuyos'),T('Four bedrooms · five beds','Cuatro habitaciones · cinco camas')),(7,'03',T('One more around the table','Uno más a la mesa'),T('Open living · a fully equipped kitchen','Sala abierta · cocina equipada'))]:
        s+=f'<a class="space-card" href="{gallery}#{"living" if i==7 else "bedrooms"}"><div>{photo(i,lang,sizes="(max-width: 700px) 85vw, 33vw")}<span class="space-number">{number}</span><span class="photo-open" aria-hidden="true">↗</span></div><h3>{title}</h3><p>{copy}</p></a>'
    s+=f'''</div></section><section class="pool-moment"><div>{photo(27,lang,sizes='100vw')}</div><div class="moment-copy"><span class="eyebrow">{T('NO PLANS IS A PLAN','NO TENER PLAN TAMBIÉN ES UN PLAN')}</span><h2>{T('Let the days<br><em>take their time.</em>','Que los días<br><em>pasen sin prisa.</em>')}</h2><p>{T('A table in the shade. A dip in the pool.<br>Your favourite people, exactly where they should be.','Una mesa a la sombra. Un chapuzón en la piscina.<br>Tus personas favoritas, justo donde deben estar.')}</p></div></section>
<section class="section experiences experience-story" id="services"><div class="section-heading"><div><span class="eyebrow">03 — {T('A LITTLE SOMETHING EXTRA','UN POCO MÁS PARA DISFRUTAR')}</span><h2>{T('Your stay.<br><em>With a personal touch.</em>','Tu estadía.<br><em>Con un toque personal.</em>')}</h2></div><p>{T('Tell us what would make it special. We’ll help coordinate the details with our local partners.','Cuéntanos qué la haría especial. Te ayudamos a coordinar los detalles con nuestros aliados locales.')}</p></div><div class="curated-experiences">'''
    for n,service,pic,title,copy in [('01','private_chef','chef',T('The table is yours','La mesa es tuya'),T('A private chef. A meal worth lingering over. Leave the cooking to someone else.','Un chef privado. Una comida para disfrutar con calma. Deja la cocina en otras manos.')),('02','in_home_massage','massage',T('A deeper kind of pause','Una pausa de verdad'),T('An in-villa massage, arranged around your day. Nothing to do but unwind.','Un masaje en la villa, coordinado a tu ritmo. Solo tienes que relajarte.')),('03','decoration','celebration',T('Make it an occasion','Hazlo especial'),T('A birthday, an anniversary, or simply being together. Tell us what you’re imagining.','Un cumpleaños, un aniversario o simplemente estar juntos. Cuéntanos qué imaginas.'))]:
        s+=f'<article class="curated-card">{image(pic,title)}<div><span class="eyebrow">{n}</span><h3>{title}</h3><p>{copy}</p><button class="text-link" data-enquire="{service}" data-placement="service">{T("Ask us about it","Consulta con nosotros")} ↗</button></div></article>'
    s+=f'''</div><div class="more-services"><span>{T('And the little things, taken care of.','Y los pequeños detalles, resueltos.')}</span><button data-enquire="airport_transfer" data-placement="service">{T('Airport transfers','Traslados del aeropuerto')} ↗</button><button data-enquire="grocery_shopping" data-placement="service">{T('Grocery shopping','Compras de supermercado')} ↗</button><button data-enquire="guided_tours" data-placement="service">{T('Local adventures','Aventuras locales')} ↗</button></div><p class="fine">{T('Every extra is arranged on request, subject to availability and an agreed quote.','Cada servicio se coordina por solicitud, sujeto a disponibilidad y una cotización acordada.')}</p></section>
<section class="section coastal-guide" id="explore"><div class="coastal-image">{image('eltunco',T('El Tunco on the Salvadoran coast','El Tunco en la costa salvadoreña'))}<span>EL SALVADOR, {T('BY THE SEA','JUNTO AL MAR')}</span></div><div><span class="eyebrow">04 — {T('A GOOD PLACE TO GET LOST','UN BUEN LUGAR PARA EXPLORAR')}</span><h2>{T('The coast is<br><em>calling.</em>','La costa<br><em>te espera.</em>')}</h2><p>{T('Surf mornings in El Tunco. Slow afternoons in El Zonte. Seafood with a view in La Libertad. Follow your curiosity, then come home to White Swan.','Mañanas de surf en El Tunco. Tardes tranquilas en El Zonte. Mariscos con vista al mar en La Libertad. Sigue tu curiosidad y vuelve a White Swan.')}</p><div class="local-places"><a href="{guide}#explore"><span>El Tunco</span><small>{T('Surf & coastal life','Surf y vida costera')}</small>↗</a><a href="{guide}#explore"><span>El Zonte</span><small>{T('A slower seaside rhythm','Otro ritmo junto al mar')}</small>↗</a><a href="{guide}#explore"><span>La Libertad</span><small>{T('Flavours of the Pacific','Sabores del Pacífico')}</small>↗</a></div><a class="text-link" href="{guide}#explore">{T('Open the local guide','Abre la guía local')} ↗</a></div></section>
<section class="section faq"><div><span class="eyebrow">05 — {T('BEFORE YOU PACK','ANTES DE HACER LAS MALETAS')}</span><h2>{T('A few useful<br><em>little details.</em>','Algunos detalles<br><em>para tu viaje.</em>')}</h2><p class="muted">{T('Have something else in mind? We’re a message away.','¿Tienes otra pregunta? Estamos a un mensaje de distancia.')}</p><a class="text-link" href="https://wa.me/50370528003" target="_blank" rel="noopener">{T('Talk to us','Conversemos')} ↗</a></div><div>'''
    faqs=[(T('How do I book my stay?','¿Cómo reservo mi estadía?'),T('Use our Airbnb listing to see current availability, guest capacity, rates and booking terms. For questions or extras, message us on WhatsApp.','Consulta disponibilidad, capacidad, tarifas y condiciones actuales en nuestro anuncio de Airbnb. Para preguntas o servicios adicionales, escríbenos por WhatsApp.')),(T('Is the pool just for us?','¿La piscina es solo para nosotros?'),T('Yes. The villa and its infinity pool are private for your group.','Sí. La villa y su piscina infinita son privadas para tu grupo.')),(T('How do we get to the beach?','¿Cómo llegamos a la playa?'),T('The community beach is reached by a downhill route with stairs. Ask us about the route before booking if anyone in your group has mobility needs.','El acceso a la playa de la comunidad incluye una bajada y gradas. Consulta sobre la ruta antes de reservar si alguien en tu grupo tiene necesidades de movilidad.')),(T('Can you help plan something special?','¿Pueden ayudarnos a planear algo especial?'),T('We can coordinate a chef, massages, groceries, transfers and celebration details. We confirm supplier availability and your quote before any service is booked.','Podemos coordinar chef, masajes, compras, traslados y detalles para celebraciones. Confirmamos disponibilidad y cotización antes de reservar cualquier servicio.')),(T('Where are the arrival details?','¿Dónde encuentro los detalles de llegada?'),T('Our guest guide has general arrival information. Private access instructions are shared with confirmed guests through Airbnb before arrival.','Nuestra guía incluye información general de llegada. Las instrucciones privadas de acceso se comparten con huéspedes confirmados por Airbnb antes de llegar.'))]
    for q,a in faqs:s+=f'<details><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>'
    s+=f'''</div></section><section class="invitation final-invitation"><div class="final-photo">{photo(31,lang,sizes='100vw')}</div><div><span class="eyebrow">{T('THE BEST PART? MAKING IT YOURS.','LO MEJOR: HACERLA TUYA.')}</span><h2>{T('See you<br><em>by the Pacific.</em>','Nos vemos<br><em>junto al Pacífico.</em>')}</h2><div class="actions"><a class="button light" href="{AIRBNB}" target="_blank" rel="noopener" data-placement="footer">{T('Find your dates','Elige tus fechas')} ↗</a><button class="hero-link" data-enquire="stay" data-placement="footer">{T('Let’s plan your stay','Planeemos tu estadía')} →</button></div></div></section></main>{footer(lang)}{components(lang)}</body></html>'''
    return s

def gallery(lang,head,components):
    T=lambda en,es:es if lang=='es' else en
    path='/es/fotos/' if lang=='es' else '/photos/';other='/photos/' if lang=='es' else '/es/fotos/'
    s=head(lang,path,T('A look around | White Swan Villa photo tour','Cada rincón | Recorrido fotográfico de White Swan'),T('Explore 36 photographs of White Swan Villa: bedrooms, open living, private infinity pool and the coast of Xanadu.','Explora 36 fotografías de White Swan: habitaciones, sala abierta, piscina infinita privada y la costa de Xanadu.'),other,'gallery')
    s+=f'<body class="editorial gallery-page" id="top">{navigation(lang,"photos")}<main id="main" class="section photo-tour"><span class="eyebrow">WHITE SWAN / {T("A CLOSER LOOK","DE CERCA")}</span><h1>{T("Picture yourself <em>here.</em>","Imagínate <em>aquí.</em>")}</h1><p class="muted">{T("The spaces, the little details, and that Pacific light.","Los espacios, los pequeños detalles y esa luz del Pacífico.")}</p><div class="gallery-filters" role="group" aria-label="{T("Filter photos","Filtrar fotos")}">'
    for key,en,es in [('all','All spaces','Todos los espacios'),('outdoors','Outdoors & pool','Exterior y piscina'),('bedrooms','Bedrooms','Habitaciones'),('living','Living & kitchen','Sala y cocina'),('details','The details','Los detalles')]:
        s+=f'<button data-photo-filter="{key}" aria-pressed="{str(key=="all").lower()}">{T(en,es)}</button>'
    s+=f'</div><p class="photo-results" role="status" aria-live="polite">36 {T("photos","fotos")}</p><div class="photo-tour-grid">'
    order=[29,32,28,31,30,27,24,35,8,9,10,11,12,13,14,15,16,17,18,1,0,2,3,4,5,6,7,19,20,21,22,23,25,26,33,34]
    for i in order:
        p=PHOTOS[i]
        s+=f'<figure data-photo-category="{p["category"]}"><a href="/assets/listing/{p["id"]}-1920.webp" data-photo-open data-caption="{escape(p["alt"][lang])}">{photo(i,lang,sizes="(max-width: 700px) 100vw, 33vw")}<span class="photo-open" aria-hidden="true">↗</span></a><figcaption>{escape(p["alt"][lang])}</figcaption></figure>'
    s+=f'''</div><noscript><p>{T('Select any photograph to open the full-size image.','Selecciona una fotografía para verla en tamaño completo.')}</p></noscript></main>{footer(lang)}<dialog class="photo-viewer" aria-label="{T('Photo viewer','Visor de fotografías')}"><div class="viewer-top"><span>WHITE SWAN</span><button data-viewer-close aria-label="{T('Close photo','Cerrar fotografía')}">×</button></div><div class="viewer-stage"><button data-photo-prev aria-label="{T('Previous photo','Foto anterior')}">←</button><img alt="" width="1600" height="1200"><button data-photo-next aria-label="{T('Next photo','Siguiente foto')}">→</button></div><div class="viewer-caption" aria-live="polite"><p></p><span></span></div></dialog>{components(lang)}</body></html>'''
    return s
