"""Editorial public pages. Shared renderer keeps English and Spanish in step."""
from html import escape
import json
from pathlib import Path
from concierge import link as whatsapp_link, section as concierge_section, widget as concierge_widget
from guestguide import destinations
from hospitality import faq_section
from photography import photo, full_photo, GALLERY_ORDER, PHOTO_COUNT, markup
ROOT = Path(__file__).resolve().parents[1]
CATALOG = json.loads((ROOT / 'content/listing-photos.json').read_text())
PHOTOS = CATALOG['photos']
AIRBNB = 'https://www.airbnb.com/rooms/47911834'
def booking_path(lang):
    return '/es/reservar/' if lang == 'es' else '/stay/'

def editorial_photo(lang):
    alt='The sunlit White Swan villa, private pool and palms — editorially enhanced photograph' if lang=='en' else 'White Swan iluminada por el sol, piscina privada y palmeras — fotografía con retoque editorial'
    return f'<picture><source type="image/avif" srcset="/assets/editorial/villa-light-640.avif 640w, /assets/editorial/villa-light-960.avif 960w, /assets/editorial/villa-light-1536.avif 1536w" sizes="(max-width: 700px) 100vw, 65vw"><img src="/assets/editorial/villa-light-960.webp" srcset="/assets/editorial/villa-light-640.webp 640w, /assets/editorial/villa-light-960.webp 960w, /assets/editorial/villa-light-1536.webp 1536w" sizes="(max-width: 700px) 100vw, 65vw" width="1536" height="1024" alt="{alt}" fetchpriority="high" decoding="async"></picture>'

def hero_scene(lang):
    T=lambda en,es:es if lang=='es' else en
    gallery='/es/fotos/' if lang=='es' else '/photos/'
    night=markup('guide-transfer',T('White Swan at night, with illuminated rooms, garden and private pool','White Swan de noche, con habitaciones, jardín y piscina privada iluminados'),sizes='(max-width: 700px) 100vw, 80vw').replace('loading="lazy"', 'loading="lazy" fetchpriority="low"')
    night='<picture><source type="image/avif" srcset="/assets/editorial/villa-night-640.avif 640w, /assets/editorial/villa-night-960.avif 960w, /assets/editorial/villa-night-1536.avif 1536w" sizes="(max-width: 700px) 100vw, 80vw">'+night+'</picture>'
    return f'''<div class="hero-photo cinematic-cover" data-scene="day" role="group" aria-label="{T('The villa, from day to night','La villa, del día a la noche')}"><div class="hero-frame hero-day" data-hero-frame="day">{editorial_photo(lang)}</div><div class="hero-frame hero-night" data-hero-frame="night" aria-hidden="true">{night}</div><a class="retouch-note" href="{gallery}">{T('Editorial photography · Explore the villa','Fotografía editorial · Explora la villa')} ↗</a><div class="hero-scene-controls" hidden><div class="hero-scene-options" role="group" aria-label="{T('Choose a moment','Elige un momento')}"><button type="button" data-hero-scene="day" aria-pressed="true"><span aria-hidden="true">01</span>{T('Daylight','De día')}</button><button type="button" data-hero-scene="night" aria-pressed="false"><span aria-hidden="true">02</span>{T('After dark','De noche')}</button></div><button type="button" class="hero-motion-toggle" data-hero-motion aria-label="{T('Pause photo animation','Pausar animación de fotos')}" title="{T('Pause photo animation','Pausar animación de fotos')}"><svg viewBox="0 0 20 20" width="18" height="18" aria-hidden="true"><path class="motion-pause" d="M7 5v10M13 5v10"/><path class="motion-play" d="m7 4 9 6-9 6z"/></svg></button></div></div>'''

def navigation(lang, active='home'):
    T=lambda en,es:es if lang=='es' else en
    stay_target='#booking' if active=='stay' else booking_path(lang)
    home='/es/' if lang=='es' else '/'
    gallery='/es/fotos/' if lang=='es' else '/photos/'
    guide='/es/guia/' if lang=='es' else '/guide/'
    other=('/stay/' if lang=='es' else '/es/reservar/') if active=='stay' else ('/photos/' if lang=='es' else '/es/fotos/') if active=='photos' else ('/' if lang=='es' else '/es/')
    if active=='guide': other='/guide/' if lang=='es' else '/es/guia/'
    if active=='privacy': other='/privacy/' if lang=='es' else '/es/privacidad/'
    return f'''<a class="skip" href="#main">{T('Skip to content','Ir al contenido')}</a>
<header class="site-header editorial-header">
 <a class="brand wordmark" href="{home}"><img src="/assets/swan-mark.svg" width="38" height="38" alt="">WHITE SWAN<small>XANADU, EL SALVADOR</small></a>
 <nav aria-label="{T('Main navigation','Navegación principal')}"><a href="{home}#villa">{T('The villa','La villa')}</a><a href="{gallery}">{T('The spaces','Los espacios')}</a><a href="{home}#services">{T('Experiences','Experiencias')}</a><a href="{home}#explore">{T('The coast','La costa')}</a><a href="{home}#concierge">{T('Concierge','Concierge')}</a><a href="{home}#faq">{T('FAQs','Preguntas')}</a></nav>
 <div class="header-actions"><a class="language" {'data-preserve-section' if active in ['guide','home'] else ''} href="{other}" aria-label="{T('Ver en español','View in English')}" lang="{T('es','en')}">{T('EN <span>/ ES</span>','ES <span>/ EN</span>')}</a><a class="button small" href="{stay_target}" data-placement="navigation">{T('Plan your stay','Planea tu estadía')} <span aria-hidden="true">→</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu" aria-label="{T('Open menu','Abrir menú')}"><span></span><span></span></button></div>
</header><nav id="mobile-menu" class="mobile-menu" aria-label="{T('Mobile navigation','Navegación móvil')}" hidden><a href="{home}#villa">{T('The villa','La villa')}</a><a href="{gallery}">{T('Photo tour','Recorrido fotográfico')}</a><a href="{home}#services">{T('Experiences','Experiencias')}</a><a href="{home}#explore">{T('The coast','La costa')}</a><a href="{home}#faq">{T('FAQs','Preguntas frecuentes')}</a><a href="{home}#concierge">Concierge</a><a href="{guide}">{T('Guest guide','Guía del huésped')}</a><a href="{stay_target}">{T('Plan your stay','Planea tu estadía')} →</a></nav>'''

def footer(lang, active="home"):
    T=lambda en,es:es if lang=='es' else en
    stay_target='#booking' if active=='stay' else booking_path(lang)
    home='/es/' if lang=='es' else '/';guide='/es/guia/' if lang=='es' else '/guide/';privacy='/es/privacidad/' if lang=='es' else '/privacy/'
    return f'''<footer class="site-footer editorial-footer"><div><a class="brand wordmark" href="{home}">WHITE SWAN<small>XANADU, EL SALVADOR</small></a><p>{T('A private place above the Pacific.','Un lugar privado sobre el Pacífico.')}<br>Tamanique · La Libertad</p></div><div><span class="eyebrow">{T('MAKE YOURSELF AT HOME','SIÉNTETE EN CASA')}</span><a href="{guide}">{T('Guest guide','Guía del huésped')}</a><a href="{home}#faq">{T('Frequently asked questions','Preguntas frecuentes')}</a><a href="{guide}#arrive">{T('Arrival & directions','Llegada e indicaciones')}</a><a href="{guide}#rules">{T('House rules','Reglas de la casa')}</a><a href="{guide}#contact">{T('Host & on-site team','Anfitrión y equipo en sitio')}</a><a href="{AIRBNB}" target="_blank" rel="noopener" data-placement="footer">Airbnb ↗</a><a href="https://wa.me/50370528003" target="_blank" rel="noopener" data-placement="footer">WhatsApp ↗</a></div><div><span class="eyebrow">{T('A LITTLE HOUSEKEEPING','ALGUNOS DETALLES')}</span><a href="{privacy}">{T('Privacy & cookies','Privacidad y cookies')}</a><button data-cookie-settings>{T('Cookie preferences','Preferencias de cookies')}</button><span>{T('We speak English & Spanish.','Hablamos español e inglés.')}</span></div><div class="footer-bottom"><span>© {2026} White Swan Villa</span><span>{T('Ocean air. Good company. Nothing rushed.','Brisa del mar. Buena compañía. Sin prisa.')}</span><a href="#top">{T('Back to top','Volver arriba')} ↑</a></div></footer><div class="mobile-bar"><span>WHITE SWAN<small>{T('Your place by the Pacific','Tu lugar junto al Pacífico')}</small></span><a class="button small" href="{stay_target}" data-placement="sticky">{T('Plan your stay','Planea tu estadía')} →</a></div>'''

def home(lang, head, image, components):
    T=lambda en,es:es if lang=='es' else en
    home='/es/' if lang=='es' else '/';guide='/es/guia/' if lang=='es' else '/guide/';gallery='/es/fotos/' if lang=='es' else '/photos/'
    s=head(lang,home,T('White Swan | A private ocean-view villa in Xanadu, El Salvador','White Swan | Villa privada con vista al mar en Xanadu, El Salvador'),T('Make the Pacific your backdrop. Four bedrooms, a private infinity pool and space to slow down at White Swan Villa in Xanadu, El Salvador.','El Pacífico como escenario. Cuatro habitaciones, piscina infinita privada y espacio para disfrutar sin prisa en White Swan, Xanadu, El Salvador.'),'/' if lang=='es' else '/es/')
    s+=f'''<body class="editorial" id="top">{navigation(lang)}<main id="main">
<section class="hero coast-hero resort-hero">{hero_scene(lang)}<div class="hero-copy"><span class="hero-ornament" aria-hidden="true">W<span>✧</span>S</span><span class="eyebrow">{T('A PRIVATE VILLA · XANADU, EL SALVADOR','VILLA PRIVADA · XANADU, EL SALVADOR')}</span><h1>{T('Somewhere<br><em>extraordinary.</em>','Un refugio<br><em>extraordinario.</em>')}</h1><p>{T('A private villa above the Pacific. Slow days by the pool. The rare pleasure of time, entirely your own.','Una villa privada sobre el Pacífico. Días tranquilos junto a la piscina. El placer de tener tiempo, solo para ustedes.')}</p><div class="actions"><a class="button" href="{booking_path(lang)}" data-placement="hero">{T('Discover your stay','Descubre tu estadía')} →</a><a class="hero-link" href="{gallery}">{T('Take a look around','Descubre cada rincón')} <span>→</span></a></div></div><div class="hero-caption"><span>WHITE SWAN · {T("THE VILLA & PRIVATE POOL","LA VILLA Y PISCINA PRIVADA")}</span><a href="#villa">{T('SLOW DOWN. SCROLL A LITTLE.','SIN PRISA. SIGUE EXPLORANDO.')} ↓</a><a class="photo-count" href="{gallery}"><span aria-hidden="true">▧</span> {T(f'{PHOTO_COUNT} photos',f'{PHOTO_COUNT} fotos')}</a></div></section>
<div class="stay-facts"><div><strong>04</strong><span>{T('Bedrooms','Habitaciones')}</span></div><div><strong>05</strong><span>{T('Beds','Camas')}</span></div><div><strong>3.5</strong><span>{T('Bathrooms','Baños')}</span></div><div><strong>∞</strong><span>{T('Private pool. Ocean views.','Piscina privada. Vista al mar.')}</span></div><a href="{booking_path(lang)}" data-placement="facts">{T('Entire villa, just for you','Toda la villa, solo para ustedes')} <span>↗</span></a></div>
<nav class="journey-nav" aria-label="{T('Explore this page','Explora esta página')}"><span>WHITE SWAN</span><a href="#villa">{T('The villa','La villa')}</a><a href="#services">{T('Experiences','Experiencias')}</a><a href="#explore">{T('The coast','La costa')}</a><a href="#faq">{T('Your stay & FAQs','Tu estadía y preguntas')}</a><a href="#concierge">Concierge</a></nav>
<section class="section villa villa-story" id="villa"><div class="intro"><span class="eyebrow">01 — {T('THIS IS WHITE SWAN','ESTO ES WHITE SWAN')}</span><h2>{T('Some places make<br>you feel <em>different.</em>','Hay lugares que<br>se sienten <em>diferentes.</em>')}</h2><p class="lead-copy">{T('The first swim before breakfast. The ocean from your pillow. A long lunch that somehow becomes sunset.','El primer chapuzón antes del desayuno. El mar desde tu almohada. Un almuerzo largo que, sin darte cuenta, se convierte en atardecer.')}</p><p class="muted">{T('White Swan is a private four-bedroom vacation villa in Xanadu, Tamanique, on El Salvador’s La Libertad coast. Your own infinity pool, Pacific views and space to share with your favourite people.','White Swan es una casa de playa privada de cuatro habitaciones en Xanadu, Tamanique, en la costa de La Libertad, El Salvador. Piscina infinita, vistas al Pacífico y espacio para compartir con los tuyos.')}</p><a class="text-link" href="{gallery}">{T('Step inside the villa','Entra a la villa')} <span>↗</span></a><div class="story-note"><span class="small-sun" aria-hidden="true">✧</span><p>{T('A whole home.<br>A slower kind of day.','Una casa entera.<br>Un día con otro ritmo.')}</p></div></div><div class="story-photos villa-diptych"><a href="{gallery}#outdoors" class="story-main">{photo(27,lang,sizes="(max-width: 700px) 100vw, 53vw")}<span>{T('Your own private villa','Tu propia villa privada')} ↗</span></a><a href="{gallery}#outdoors" class="story-inset">{photo(28,lang,sizes="(max-width: 700px) 100vw, 30vw")}<span>{T('The infinity pool. The Pacific.','La piscina infinita. El Pacífico.')} ↗</span></a></div></section>
<section class="section space-section" id="spaces"><div class="section-heading"><div><span class="eyebrow">02 — {T('ROOM TO MAKE MEMORIES','ESPACIO PARA CREAR RECUERDOS')}</span><h2>{T('Come together.<br><em>Find your own quiet.</em>','Compartan momentos.<br><em>Encuentren su calma.</em>')}</h2></div><div><p>{T('Four bedrooms upstairs. Open living below. And the Pacific, never far from view.','Cuatro habitaciones arriba. Espacios abiertos abajo. Y el Pacífico, siempre cerca.')}</p><a class="text-link" href="{gallery}">{T(f'Explore all {PHOTO_COUNT} photos',f'Explora las {PHOTO_COUNT} fotos')} ↗</a></div></div><div class="space-grid">'''
    for i,number,title,copy in [(9,'01',T('Wake up to the Pacific','Despierta frente al Pacífico'),T('The primary bedroom · ocean views','La habitación principal · vista al mar')),(1,'02',T('Make yourself at home','Siéntete en casa'),T('Light-filled living · room to gather','Sala llena de luz · espacio para compartir')),(4,'03',T('Good mornings start here','Las mañanas empiezan aquí'),T('A fully equipped kitchen','Una cocina totalmente equipada'))]:
        s+=f'<a class="space-card" href="{gallery}#{"bedrooms" if i==9 else "living"}"><div>{photo(i,lang,sizes="(max-width: 700px) 170vw, 66vw")}<span class="space-number">{number}</span><span class="photo-open" aria-hidden="true">↗</span></div><h3>{title}</h3><p>{copy}</p></a>'
    s+='</div></section>'+guest_reviews(lang)
    s+=f'''
<section class="section experiences experience-story services-simple" id="services"><div class="section-heading"><div><span class="eyebrow">03 — {T('A LITTLE SOMETHING EXTRA','UN POCO MÁS PARA DISFRUTAR')}</span><h2>{T('Make it <em>yours.</em>','Hazla <em>tuya.</em>')}</h2></div><p>{T('Choose a service. Tell us your plans on WhatsApp. We’ll take care of the details.','Elige un servicio. Cuéntanos tus planes por WhatsApp. Coordinamos los detalles.')}</p></div><div class="curated-experiences">'''
    services=[
        ('private_chef',3,T('Private chef','Chef privado'),T('A freshly prepared meal, enjoyed here at the villa.','Una comida recién preparada, aquí en la villa.'),T('Ask about a chef','Consultar por un chef')),
        ('in_home_massage',12,T('In-villa massage','Masajes en la villa'),T('Take time for yourself. We’ll help arrange your massage.','Un momento para ti. Te ayudamos a coordinar tu masaje.'),T('Ask about a massage','Consultar por un masaje')),
        ('decoration',7,T('Celebrations','Celebraciones'),T('A birthday, an anniversary, a moment worth celebrating.','Un cumpleaños, un aniversario, un momento para celebrar.'),T('Plan a celebration','Planear una celebración')),
    ]
    for service,pic,title,copy,cta in services:
        s+=f'<article class="curated-card">{photo(pic,lang,sizes="(max-width: 700px) 100vw, 40vw")}<div><h3>{title}</h3><p>{copy}</p>{whatsapp_link(lang,service,home+"#services",label=cta,classes="button light service-cta")}</div></article>'
    s+=f'''</div><div class="services-foot"><p>{T('On request. Price and availability confirmed before booking.','Por solicitud. Precio y disponibilidad confirmados antes de reservar.')}</p><a class="text-link" href="{guide}#services">{T('All services & prices','Todos los servicios y precios')} →</a></div></section>
{destinations(lang,home,embedded=True)}{faq_section(lang)}{concierge_section(lang)}<section class="invitation final-invitation" id="book"><div class="final-photo">{image('transfer',T('White Swan illuminated above its pool and garden at night','White Swan iluminada junto a su piscina y jardín de noche'))}</div><div><span class="eyebrow">{T('THE BEST PART? MAKING IT YOURS.','LO MEJOR: HACERLA TUYA.')}</span><h2>{T('See you<br><em>by the Pacific.</em>','Nos vemos<br><em>junto al Pacífico.</em>')}</h2><div class="actions"><a class="button light" href="{booking_path(lang)}" data-placement="footer">{T('Plan your stay','Planea tu estadía')} →</a><button class="hero-link" data-enquire="stay" data-placement="footer">{T('Ask us about your stay','Consúltanos sobre tu estadía')} →</button></div></div></section></main>{footer(lang)}{concierge_widget(lang,home)}{components(lang)}</body></html>'''
    return s

def gallery(lang,head,components):
    T=lambda en,es:es if lang=='es' else en
    path='/es/fotos/' if lang=='es' else '/photos/';other='/photos/' if lang=='es' else '/es/fotos/'
    s=head(lang,path,T('A look around | White Swan Villa photo tour','Cada rincón | Recorrido fotográfico de White Swan'),T('Explore 35 photographs of White Swan Villa: bedrooms, open living, private infinity pool and the coast of Xanadu.','Explora 35 fotografías de White Swan: habitaciones, sala abierta, piscina infinita privada y la costa de Xanadu.'),other,'gallery')
    s+=f'<body class="editorial gallery-page" id="top">{navigation(lang,"photos")}<main id="main" class="section photo-tour"><span class="eyebrow">WHITE SWAN / {T("A CLOSER LOOK","DE CERCA")}</span><h1>{T("Picture yourself <em>here.</em>","Imagínate <em>aquí.</em>")}</h1><p class="muted">{T("The spaces, the little details, and that Pacific light. Photographs with an editorial finish.","Los espacios, los pequeños detalles y esa luz del Pacífico. Fotografías con retoque editorial.")}</p><div class="gallery-filters" role="group" aria-label="{T("Filter photos","Filtrar fotos")}">'
    for key,en,es in [('all','All spaces','Todos los espacios'),('outdoors','Outdoors & pool','Exterior y piscina'),('bedrooms','Bedrooms','Habitaciones'),('living','Living & kitchen','Sala y cocina'),('details','The details','Los detalles')]:
        s+=f'<button data-photo-filter="{key}" aria-pressed="{str(key=="all").lower()}">{T(en,es)}</button>'
    s+=f'</div><p class="photo-results" role="status" aria-live="polite">{PHOTO_COUNT} {T("photos","fotos")}</p><div class="photo-tour-grid" data-gallery-layout="all">'
    order=GALLERY_ORDER
    for position,i in enumerate(order):
        p=PHOTOS[i]
        s+=f'<figure data-photo-category="{p["category"]}"><a href="{full_photo(i)}" data-photo-open data-caption="{escape(p["alt"][lang])}">{photo(i,lang,hero=position==0,sizes="(max-width: 700px) 100vw, 90vw" if position==0 else "(max-width: 700px) 100vw, 33vw")}<span class="photo-open" aria-hidden="true">↗</span></a><figcaption><span class="photo-index" aria-hidden="true">{position+1:02d}</span><span>{escape(p["alt"][lang])}</span></figcaption></figure>'
    s+=f'''</div><noscript><p>{T('Select any photograph to open the full-size image.','Selecciona una fotografía para verla en tamaño completo.')}</p></noscript><section class="gallery-invitation"><div><span class="eyebrow">{T('FROM PICTURES TO PLANS','DE LAS FOTOS A LOS PLANES')}</span><h2>{T('Now imagine<br><em>a few days here.</em>','Ahora imagina<br><em>unos días aquí.</em>')}</h2></div><div><p>{T('Your own villa. Your favourite people. A little time by the Pacific.','Tu propia villa. Tus personas favoritas. Unos días junto al Pacífico.')}</p><a class="button" href="{booking_path(lang)}">{T('Plan your stay','Planea tu estadía')} →</a>{whatsapp_link(lang,'villa',path,label=T('A question about the villa?','¿Una pregunta sobre la villa?'))}</div></section></main>{footer(lang)}{concierge_widget(lang,path)}<dialog class="photo-viewer" aria-label="{T('Photo viewer','Visor de fotografías')}"><div class="viewer-top"><span>WHITE SWAN</span><button data-viewer-close aria-label="{T('Close photo','Cerrar fotografía')}">×</button></div><div class="viewer-stage"><button data-photo-prev aria-label="{T('Previous photo','Foto anterior')}">←</button><img alt="" width="1600" height="1200"><button data-photo-next aria-label="{T('Next photo','Siguiente foto')}">→</button></div><div class="viewer-caption" aria-live="polite"><p></p><span></span></div></dialog>{components(lang)}</body></html>'''
    return s

def guest_reviews(lang):
    T=lambda en,es:es if lang=='es' else en
    data=json.loads((ROOT/'content/guest-reviews.json').read_text())
    months={'en':['January','February','March','April','May','June','July','August','September','October','November','December'],'es':['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']}
    s=f'''<section class="section guest-stories" id="guest-stories" aria-labelledby="reviews-heading"><div class="section-heading"><div><span class="eyebrow">{T('IN OUR GUESTS’ WORDS','EN PALABRAS DE NUESTROS HUÉSPEDES')}</span><h2 id="reviews-heading">{T('The memories<br><em>they took home.</em>','Los recuerdos<br><em>que se llevaron.</em>')}</h2></div><div><p>{T('A few favourite notes from guests who made White Swan their own.','Algunas de nuestras reseñas favoritas de quienes hicieron de White Swan su hogar.')}</p><a class="text-link" href="{data['source_url']}" target="_blank" rel="noopener">{T('Read reviews on Airbnb','Lee las reseñas en Airbnb')} ↗</a></div></div><div class="guest-review-grid">'''
    for review_index,r in enumerate(data['reviews'][lang]):
        year,month,_=r['date'].split('-');date=months[lang][int(month)-1]+' '+year
        s+=f'''<figure class="guest-review {'review-featured' if review_index==0 else ''}"><div class="review-stars" aria-label="{T('5 out of 5 stars','5 de 5 estrellas')}"><span aria-hidden="true">★★★★★</span><span>5 / 5</span></div><blockquote><p lang="{lang}">“{escape(r['text'])}”</p></blockquote><figcaption><span>{T('Airbnb guest','Huésped de Airbnb')}</span><time datetime="{r['date']}">{date}</time></figcaption></figure>'''
    from datetime import date
    refreshed=date.fromisoformat(data['retrieved_at'])
    stamp=f"{refreshed.day} {months[lang][refreshed.month-1]} {refreshed.year}"
    return s+f'''</div><p class="fine review-source">{T('Selected five-star Airbnb reviews · In our guests’ own words · Collected','Reseñas seleccionadas de cinco estrellas en Airbnb · Palabras originales de los huéspedes · Consultadas el')} {stamp}.</p></section>'''

def stay(lang,head,components):
    T=lambda en,es:es if lang=='es' else en
    target=booking_path(lang); other=booking_path('en' if lang=='es' else 'es')
    # Only use the exact property-specific embed exported by Hospitable after Direct setup.
    import re
    widget=(ROOT/'content/hospitable-widget.html.template').read_text()
    widget=re.sub(r'<!--.*?-->','',widget,flags=re.S).strip()
    steps = '' if widget else f'''<ol class="stay-steps"><li><span>01</span><div><h3>{T('Choose your days','Elige tus fechas')}</h3><p>{T('Tell us when and who is coming.','Cuéntanos cuándo y quiénes vienen.')}</p></div></li><li><span>02</span><div><h3>{T('Make it personal','Hazla a tu medida')}</h3><p>{T('Talk with your host about the details.','Habla con tu anfitrión sobre los detalles.')}</p></div></li><li><span>03</span><div><h3>{T('Confirm together','Confirma con nosotros')}</h3><p>{T('Agree availability, price and booking terms.','Acuerden disponibilidad, precio y condiciones.')}</p></div></li></ol>'''
    s=head(lang,target,T('Plan your stay | White Swan Villa','Planea tu estadía | White Swan'),T('Plan your private villa escape at White Swan in Xanadu, El Salvador. Choose your dates and speak with your host.','Planea tu escapada a White Swan en Xanadu, El Salvador. Elige tus fechas y habla con tu anfitrión.'),other,'stay')
    s+=f'''<body class="editorial stay-page" id="top">{navigation(lang,'stay')}<main id="main"><section class="section stay-intro"><div><span class="eyebrow">{T('YOUR TIME AT WHITE SWAN','TU TIEMPO EN WHITE SWAN')}</span><h1>{T('A place for<br><em>your next chapter.</em>','Un lugar para<br><em>tu próxima historia.</em>')}</h1><p>{T('The whole villa. Your favourite people. Let’s find the right days for you.','Toda la villa. Tus personas favoritas. Busquemos los días perfectos para ustedes.')}</p><a class="text-link" href="#booking">{T('Choose your days','Elige tus fechas')} ↓</a></div><div class="stay-photo">{photo(29,lang,True)}<span>{T('Four bedrooms · Private infinity pool','Cuatro habitaciones · Piscina infinita privada')}</span></div></section><section class="section stay-booking" id="booking"><div class="stay-aside"><span class="eyebrow">{T('A STAY, MADE PERSONAL','UNA ESTADÍA A TU MEDIDA')}</span><h2>{T('Begin with<br><em>a few days away.</em>','Empieza con<br><em>unos días de descanso.</em>')}</h2><p>{T('From a quiet weekend to a long-awaited reunion, we’ll help you plan the details.','Desde un fin de semana tranquilo hasta un reencuentro esperado, te ayudamos con los detalles.')}</p><dl><div><dt>{T('Your space','Tu espacio')}</dt><dd>{T('Entire private villa','Villa privada completa')}</dd></div><div><dt>{T('The setting','El entorno')}</dt><dd>Xanadu · El Salvador</dd></div><div><dt>{T('Something extra','Un toque especial')}</dt><dd>{T('Chef, massage & more, on request','Chef, masajes y más, por solicitud')}</dd></div></dl>{steps}</div><div class="booking-card">'''
    if widget:
        s+=f'''<span class="eyebrow">{T('RESERVE YOUR STAY','RESERVA TU ESTADÍA')}</span><h2>{T('Find your dates.','Elige tus fechas.')}</h2><div class="hospitable-widget" data-booking-provider="hospitable">{widget}</div><p class="fine">{T('Your booking follows the price, payment terms and cancellation policy shown in the booking flow.','Tu reserva se rige por el precio, las condiciones de pago y la política de cancelación indicados al reservar.')}</p><a class="text-link" href="https://wa.me/50370528003" target="_blank" rel="noopener">{T('Need help? Talk to your host','¿Necesitas ayuda? Habla con tu anfitrión')} ↗</a>'''
    else:
        s+=f'''<span class="eyebrow">{T('PLAN WITH YOUR HOST','PLANEA CON TU ANFITRIÓN')}</span><h2>{T('When would you<br><em>like to escape?</em>','¿Cuándo te gustaría<br><em>escaparte?</em>')}</h2><p class="booking-mode-note">{T('Share your preferred dates and group size. Your host will confirm availability, the full price and the details with you on WhatsApp.','Comparte tus fechas preferidas y el tamaño del grupo. Tu anfitrión confirma disponibilidad, precio total y detalles contigo por WhatsApp.')}</p><form id="stay-request" hidden><div class="booking-fields"><label>{T('Arrival','Llegada')}<input type="date" name="arrival" required></label><label>{T('Departure','Salida')}<input type="date" name="departure" required></label><label class="guest-field">{T('Guests','Huéspedes')}<select name="guests">{''.join(f'<option value="{i}">{i} '+T('guest' if i==1 else 'guests','huésped' if i==1 else 'huéspedes')+'</option>' for i in range(1,9))}<option value="larger">{T('Larger group — ask us','Grupo más grande — consultar')}</option></select></label></div><p class="fine">{T('We confirm the permitted group size with your dates. No availability or price is confirmed by this form.','Confirmamos el tamaño permitido del grupo junto con tus fechas. Este formulario no confirma disponibilidad ni precio.')}</p><p class="stay-duration" role="status" aria-live="polite" hidden></p><p id="stay-error" class="form-status" role="alert"></p><button type="submit" class="button">{T('Review my stay request','Revisar mi solicitud')} →</button></form><noscript><p>{T('Contact your host with your dates and group size.','Contacta al anfitrión con tus fechas y el tamaño del grupo.')}</p><a class="button" href="https://wa.me/50370528003" target="_blank" rel="noopener">WhatsApp ↗</a></noscript><div id="stay-summary" hidden aria-labelledby="stay-summary-title" tabindex="-1"><h3 id="stay-summary-title">{T('Your stay, at a glance.','Tu estadía, en un vistazo.')}</h3><p class="stay-selection"></p><p>{T('Your request is ready to send. Nothing has been sent or reserved yet. Your host will confirm availability, the full price and booking terms.','Tu solicitud está lista para enviar. Aún no se ha enviado ni reservado nada. Tu anfitrión confirmará disponibilidad, precio total y condiciones.')}</p><a class="button stay-whatsapp" href="https://wa.me/50370528003" target="_blank" rel="noopener">{T('Send request on WhatsApp','Enviar solicitud por WhatsApp')} ↗</a><button class="text-link" type="button" id="edit-stay">{T('Change my dates','Cambiar mis fechas')}</button></div><p class="fine booking-footnote">{T('No payment is taken here. Your stay is confirmed only after the host accepts your booking and you meet the agreed payment terms.','Aquí no se cobra ningún pago. Tu estadía se confirma cuando el anfitrión acepta la reserva y cumples las condiciones de pago acordadas.')}</p>'''
    s+=f'''</div></section><div class="section stay-help"><p>{T('A question before you decide?','¿Una pregunta antes de decidir?')}</p><a class="text-link" href="https://wa.me/50370528003" target="_blank" rel="noopener">{T('Speak with your host','Habla con tu anfitrión')} ↗</a><a class="text-link" href="{AIRBNB}" target="_blank" rel="noopener">{T('Prefer Airbnb? View our listing','¿Prefieres Airbnb? Ver el anuncio')} ↗</a></div></main>{footer(lang,'stay')}{concierge_widget(lang,target)}{components(lang)}<script src="/assets/booking.js" defer></script></body></html>'''
    return s
