"""Editorial public pages. Shared renderer keeps English and Spanish in step."""
from html import escape
import json
from pathlib import Path
from concierge import link as whatsapp_link, section as concierge_section, widget as concierge_widget
from PIL import Image
ROOT = Path(__file__).resolve().parents[1]
CATALOG = json.loads((ROOT / 'content/listing-photos.json').read_text())
PHOTOS = CATALOG['photos']
AIRBNB = 'https://www.airbnb.com/rooms/47911834'
def booking_path(lang):
    return '/es/reservar/' if lang == 'es' else '/stay/'

def photo(index, lang, hero=False, sizes='(max-width: 700px) 100vw, 50vw'):
    p = PHOTOS[index]
    sources = {}
    for size in [480,960,1600,1920]:
        path = f"/assets/listing/{p['id']}-{size}.webp"
        with Image.open(ROOT / path.lstrip('/')) as im:
            sources.setdefault(im.width, path)
            w,h = im.size
    srcset = ', '.join(f'{url} {width}w' for width,url in sources.items())
    load = 'fetchpriority="high"' if hero else 'loading="lazy"'
    return f'<img src="/assets/listing/{p["id"]}-960.webp" srcset="{srcset}" sizes="{sizes}" width="{w}" height="{h}" alt="{escape(p["alt"][lang])}" {load} decoding="async">'

def navigation(lang, active='home'):
    T=lambda en,es:es if lang=='es' else en
    stay_target='#booking' if active=='stay' else booking_path(lang)
    home='/es/' if lang=='es' else '/'
    gallery='/es/fotos/' if lang=='es' else '/photos/'
    guide='/es/guia/' if lang=='es' else '/guide/'
    other=('/stay/' if lang=='es' else '/es/reservar/') if active=='stay' else ('/photos/' if lang=='es' else '/es/fotos/') if active=='photos' else ('/' if lang=='es' else '/es/')
    return f'''<a class="skip" href="#main">{T('Skip to content','Ir al contenido')}</a>
<header class="site-header editorial-header">
 <a class="brand wordmark" href="{home}" aria-label="White Swan — {T('home','inicio')}"><img src="/assets/favicon.svg" width="30" height="30" alt="">WHITE SWAN<small>XANADU, EL SALVADOR</small></a>
 <nav aria-label="{T('Main navigation','Navegación principal')}"><a href="{home}#villa">{T('The villa','La villa')}</a><a href="{gallery}">{T('The spaces','Los espacios')}</a><a href="{home}#services">{T('Experiences','Experiencias')}</a><a href="{home}#explore">{T('The coast','La costa')}</a><a href="{home}#concierge">{T('Concierge','Concierge')}</a></nav>
 <div class="header-actions"><a class="language" href="{other}" aria-label="{T('Ver en español','View in English')}" lang="{T('es','en')}">{T('EN <span>/ ES</span>','ES <span>/ EN</span>')}</a><a class="button small" href="{stay_target}" data-placement="navigation">{T('Plan your stay','Planea tu estadía')} <span aria-hidden="true">→</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu" aria-label="{T('Open menu','Abrir menú')}"><span></span><span></span></button></div>
</header><nav id="mobile-menu" class="mobile-menu" aria-label="{T('Mobile navigation','Navegación móvil')}" hidden><a href="{home}#villa">{T('The villa','La villa')}</a><a href="{gallery}">{T('Photo tour','Recorrido fotográfico')}</a><a href="{home}#services">{T('Experiences','Experiencias')}</a><a href="{home}#concierge">Concierge</a><a href="{guide}">{T('Guest guide','Guía del huésped')}</a><a href="{stay_target}">{T('Plan your stay','Planea tu estadía')} →</a></nav>'''

def footer(lang, active="home"):
    T=lambda en,es:es if lang=='es' else en
    stay_target='#booking' if active=='stay' else booking_path(lang)
    home='/es/' if lang=='es' else '/';guide='/es/guia/' if lang=='es' else '/guide/';privacy='/es/privacidad/' if lang=='es' else '/privacy/'
    return f'''<footer class="site-footer editorial-footer"><div><a class="brand wordmark" href="{home}">WHITE SWAN<small>XANADU, EL SALVADOR</small></a><p>{T('A private place above the Pacific.','Un lugar privado sobre el Pacífico.')}<br>Tamanique · La Libertad</p></div><div><span class="eyebrow">{T('MAKE YOURSELF AT HOME','SIÉNTETE EN CASA')}</span><a href="{guide}">{T('Guest guide','Guía del huésped')}</a><a href="{AIRBNB}" target="_blank" rel="noopener" data-placement="footer">Airbnb ↗</a><a href="https://wa.me/50370528003" target="_blank" rel="noopener" data-placement="footer">WhatsApp ↗</a></div><div><span class="eyebrow">{T('A LITTLE HOUSEKEEPING','ALGUNOS DETALLES')}</span><a href="{privacy}">{T('Privacy & cookies','Privacidad y cookies')}</a><button data-cookie-settings>{T('Cookie preferences','Preferencias de cookies')}</button><span>{T('We speak English & Spanish.','Hablamos español e inglés.')}</span></div><div class="footer-bottom"><span>© {2026} White Swan Villa</span><span>{T('Ocean air. Good company. Nothing rushed.','Brisa del mar. Buena compañía. Sin prisa.')}</span><a href="#top">{T('Back to top','Volver arriba')} ↑</a></div></footer><div class="mobile-bar"><span>WHITE SWAN<small>{T('Your place by the Pacific','Tu lugar junto al Pacífico')}</small></span><a class="button small" href="{stay_target}" data-placement="sticky">{T('Plan your stay','Planea tu estadía')} →</a></div>'''

def home(lang, head, image, components):
    T=lambda en,es:es if lang=='es' else en
    home='/es/' if lang=='es' else '/';guide='/es/guia/' if lang=='es' else '/guide/';gallery='/es/fotos/' if lang=='es' else '/photos/'
    s=head(lang,home,T('White Swan | A private ocean-view villa in Xanadu, El Salvador','White Swan | Villa privada con vista al mar en Xanadu, El Salvador'),T('Make the Pacific your backdrop. Four bedrooms, a private infinity pool and space to slow down at White Swan Villa in Xanadu, El Salvador.','El Pacífico como escenario. Cuatro habitaciones, piscina infinita privada y espacio para disfrutar sin prisa en White Swan, Xanadu, El Salvador.'),'/' if lang=='es' else '/es/')
    s+=f'''<body class="editorial" id="top">{navigation(lang)}<main id="main">
<section class="hero coast-hero resort-hero"><div class="hero-photo">{photo(29,lang,True,'(max-width: 700px) 100vw, 68vw')}</div><div class="hero-copy"><span class="eyebrow">{T('A PRIVATE VILLA · XANADU, EL SALVADOR','VILLA PRIVADA · XANADU, EL SALVADOR')}</span><h1>{T('Your private<br><em>Pacific retreat.</em>','Tu refugio<br><em>en el Pacífico.</em>')}</h1><p>{T('Sunlit spaces. Palms by the pool. The quiet pleasure of having it all to yourselves.','Espacios llenos de luz. Palmeras junto a la piscina. El placer de disfrutarlo todo, solo para ustedes.')}</p><div class="actions"><a class="button" href="{booking_path(lang)}" data-placement="hero">{T('Discover your stay','Descubre tu estadía')} →</a><a class="hero-link" href="{gallery}">{T('Take a look around','Descubre cada rincón')} <span>→</span></a></div></div><div class="hero-caption"><span>WHITE SWAN · {T("THE VILLA & PRIVATE POOL","LA VILLA Y PISCINA PRIVADA")}</span><a href="#villa">{T('SLOW DOWN. SCROLL A LITTLE.','SIN PRISA. SIGUE EXPLORANDO.')} ↓</a><a class="photo-count" href="{gallery}"><span aria-hidden="true">▧</span> {T('36 photos','36 fotos')}</a></div></section>
<div class="stay-facts"><div><strong>04</strong><span>{T('Bedrooms','Habitaciones')}</span></div><div><strong>05</strong><span>{T('Beds','Camas')}</span></div><div><strong>3.5</strong><span>{T('Bathrooms','Baños')}</span></div><div><strong>∞</strong><span>{T('Private pool. Ocean views.','Piscina privada. Vista al mar.')}</span></div><a href="{booking_path(lang)}" data-placement="facts">{T('Entire villa, just for you','Toda la villa, solo para ustedes')} <span>↗</span></a></div>
<section class="section villa villa-story" id="villa"><div class="intro"><span class="eyebrow">01 — {T('THIS IS WHITE SWAN','ESTO ES WHITE SWAN')}</span><h2>{T('Some places make<br>you feel <em>different.</em>','Hay lugares que<br>se sienten <em>diferentes.</em>')}</h2><p class="lead-copy">{T('The first swim before breakfast. The ocean from your pillow. A long lunch that somehow becomes sunset.','El primer chapuzón antes del desayuno. El mar desde tu almohada. Un almuerzo largo que, sin darte cuenta, se convierte en atardecer.')}</p><p class="muted">{T('Welcome to your own place above the Pacific. Set in the coastal community of Xanadu, White Swan brings your favourite people together — with room to spread out, settle in and simply be.','Bienvenidos a su lugar sobre el Pacífico. En la comunidad costera de Xanadu, White Swan reúne a tus personas favoritas, con espacio para compartir, descansar y disfrutar a su manera.')}</p><a class="text-link" href="{gallery}">{T('Step inside the villa','Entra a la villa')} <span>↗</span></a><div class="story-note"><span class="small-sun" aria-hidden="true">✳</span><p>{T('A whole home.<br>A slower kind of day.','Una casa entera.<br>Un día con otro ritmo.')}</p></div></div><div class="story-photos"><a href="{gallery}#outdoors" class="story-main">{photo(32,lang)}</a><a href="{gallery}#outdoors" class="story-inset">{photo(30,lang)}</a><span class="vertical-note">WHITE SWAN / {T('LIFE AT YOUR PACE','LA VIDA A TU RITMO')}</span></div></section>
<section class="section space-section" id="spaces"><div class="section-heading"><div><span class="eyebrow">02 — {T('ROOM TO MAKE MEMORIES','ESPACIO PARA CREAR RECUERDOS')}</span><h2>{T('Come together.<br><em>Find your own quiet.</em>','Compartan momentos.<br><em>Encuentren su calma.</em>')}</h2></div><div><p>{T('Four bedrooms upstairs. Open living below. And the Pacific, never far from view.','Cuatro habitaciones arriba. Espacios abiertos abajo. Y el Pacífico, siempre cerca.')}</p><a class="text-link" href="{gallery}">{T('Explore all 36 photos','Explora las 36 fotos')} ↗</a></div></div><div class="space-grid">'''
    for i,number,title,copy in [(9,'01',T('Wake up to the Pacific','Despierta frente al Pacífico'),T('The primary bedroom · ocean views','La habitación principal · vista al mar')),(1,'02',T('Make yourself at home','Siéntete en casa'),T('Light-filled living · room to gather','Sala llena de luz · espacio para compartir')),(7,'03',T('One more around the table','Uno más a la mesa'),T('Open living · a fully equipped kitchen','Sala abierta · cocina equipada'))]:
        s+=f'<a class="space-card" href="{gallery}#{"living" if i in [1,7] else "bedrooms"}"><div>{photo(i,lang,sizes="(max-width: 700px) 85vw, 33vw")}<span class="space-number">{number}</span><span class="photo-open" aria-hidden="true">↗</span></div><h3>{title}</h3><p>{copy}</p></a>'
    s+='</div></section>'+day_story(lang)+guest_reviews(lang)
    s+=f'''
<section class="section experiences experience-story" id="services"><div class="section-heading"><div><span class="eyebrow">03 — {T('A LITTLE SOMETHING EXTRA','UN POCO MÁS PARA DISFRUTAR')}</span><h2>{T('Your stay.<br><em>With a personal touch.</em>','Tu estadía.<br><em>Con un toque personal.</em>')}</h2></div><p>{T('Tell us what would make it special. We’ll help coordinate the details with our local partners.','Cuéntanos qué la haría especial. Te ayudamos a coordinar los detalles con nuestros aliados locales.')}</p></div><div class="curated-experiences">'''
    for n,service,pic,title,copy in [('01','private_chef','chef',T('The table is yours','La mesa es tuya'),T('A private chef. A meal worth lingering over. Leave the cooking to someone else.','Un chef privado. Una comida para disfrutar con calma. Deja la cocina en otras manos.')),('02','in_home_massage','massage',T('A deeper kind of pause','Una pausa de verdad'),T('An in-villa massage, arranged around your day. Nothing to do but unwind.','Un masaje en la villa, coordinado a tu ritmo. Solo tienes que relajarte.')),('03','decoration','celebration',T('Make it an occasion','Hazlo especial'),T('A birthday, an anniversary, or simply being together. Tell us what you’re imagining.','Un cumpleaños, un aniversario o simplemente estar juntos. Cuéntanos qué imaginas.'))]:
        s+=f'<article class="curated-card">{image(pic,title)}<div><span class="eyebrow">{n}</span><h3>{title}</h3><p>{copy}</p>{whatsapp_link(lang,service,home+"#services",label=T("Ask on WhatsApp","Consultar por WhatsApp"))}</div></article>'
    s+=f'''</div><div class="more-services"><span>{T('And the little things, taken care of.','Y los pequeños detalles, resueltos.')}</span>{whatsapp_link(lang,"airport_transfer",home+"#services",label=T("Airport transfers","Traslados del aeropuerto"))}{whatsapp_link(lang,"grocery_shopping",home+"#services",label=T("Grocery shopping","Compras de supermercado"))}{whatsapp_link(lang,"guided_tours",home+"#services",label=T("Local adventures","Aventuras locales"))}</div><p class="fine">{T('Every extra is arranged on request, subject to availability and an agreed quote.','Cada servicio se coordina por solicitud, sujeto a disponibilidad y una cotización acordada.')}</p></section>
<section class="section coastal-guide" id="explore"><div class="coastal-image">{photo(35,lang)}<span>EL SALVADOR, {T('BY THE SEA','JUNTO AL MAR')}</span></div><div><span class="eyebrow">04 — {T('A GOOD PLACE TO GET LOST','UN BUEN LUGAR PARA EXPLORAR')}</span><h2>{T('The coast is<br><em>calling.</em>','La costa<br><em>te espera.</em>')}</h2><p>{T('Surf mornings in El Tunco. Slow afternoons in El Zonte. Seafood with a view in La Libertad. Follow your curiosity, then come home to White Swan.','Mañanas de surf en El Tunco. Tardes tranquilas en El Zonte. Mariscos con vista al mar en La Libertad. Sigue tu curiosidad y vuelve a White Swan.')}</p><div class="local-places"><a href="{guide}#explore"><span>El Tunco</span><small>{T('Surf & coastal life','Surf y vida costera')}</small>↗</a><a href="{guide}#explore"><span>El Zonte</span><small>{T('A slower seaside rhythm','Otro ritmo junto al mar')}</small>↗</a><a href="{guide}#explore"><span>La Libertad</span><small>{T('Flavours of the Pacific','Sabores del Pacífico')}</small>↗</a></div><a class="text-link" href="{guide}#explore">{T('Open the local guide','Abre la guía local')} ↗</a></div></section>
{concierge_section(lang)}<section class="section faq"><div><span class="eyebrow">05 — {T('BEFORE YOU PACK','ANTES DE HACER LAS MALETAS')}</span><h2>{T('A few useful<br><em>little details.</em>','Algunos detalles<br><em>para tu viaje.</em>')}</h2><p class="muted">{T('Have something else in mind? We’re a message away.','¿Tienes otra pregunta? Estamos a un mensaje de distancia.')}</p><a class="text-link" href="https://wa.me/50370528003" target="_blank" rel="noopener">{T('Talk to us','Conversemos')} ↗</a></div><div>'''
    faqs=[(T('How do I book my stay?','¿Cómo reservo mi estadía?'),T('Start with Plan your stay to choose your preferred dates and group size on this website. While online booking is being connected, send your request to our host on WhatsApp. We confirm availability, the full price and terms before you commit; selecting dates does not reserve them.','En Planea tu estadía puedes elegir tus fechas y el tamaño de tu grupo en esta web. Mientras conectamos las reservas en línea, envía tu solicitud al anfitrión por WhatsApp. Confirmamos disponibilidad, precio total y condiciones antes de reservar; elegir fechas no las bloquea.')),(T('Is the pool just for us?','¿La piscina es solo para nosotros?'),T('Yes. The villa and its infinity pool are private for your group.','Sí. La villa y su piscina infinita son privadas para tu grupo.')),(T('How do we get to the beach?','¿Cómo llegamos a la playa?'),T('The community beach is reached by a downhill route with stairs. Ask us about the route before booking if anyone in your group has mobility needs.','El acceso a la playa de la comunidad incluye una bajada y gradas. Consulta sobre la ruta antes de reservar si alguien en tu grupo tiene necesidades de movilidad.')),(T('Can you help plan something special?','¿Pueden ayudarnos a planear algo especial?'),T('We can coordinate a chef, massages, groceries, transfers and celebration details. We confirm supplier availability and your quote before any service is booked.','Podemos coordinar chef, masajes, compras, traslados y detalles para celebraciones. Confirmamos disponibilidad y cotización antes de reservar cualquier servicio.')),(T('Where are the arrival details?','¿Dónde encuentro los detalles de llegada?'),T('Our guest guide has general arrival information. Private access instructions are shared with confirmed guests through Airbnb before arrival.','Nuestra guía incluye información general de llegada. Las instrucciones privadas de acceso se comparten con huéspedes confirmados por Airbnb antes de llegar.'))]
    for q,a in faqs:s+=f'<details><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>'
    s+=f'''</div></section><section class="invitation final-invitation"><div class="final-photo">{image('transfer',T('White Swan illuminated above its pool and garden at night','White Swan iluminada junto a su piscina y jardín de noche'))}</div><div><span class="eyebrow">{T('THE BEST PART? MAKING IT YOURS.','LO MEJOR: HACERLA TUYA.')}</span><h2>{T('See you<br><em>by the Pacific.</em>','Nos vemos<br><em>junto al Pacífico.</em>')}</h2><div class="actions"><a class="button light" href="{booking_path(lang)}" data-placement="footer">{T('Plan your stay','Planea tu estadía')} →</a><button class="hero-link" data-enquire="stay" data-placement="footer">{T('Let’s plan your stay','Planeemos tu estadía')} →</button></div></div></section></main>{footer(lang)}{concierge_widget(lang,home)}{components(lang)}</body></html>'''
    return s

def day_story(lang):
    T=lambda en,es:es if lang=='es' else en
    moments=[('morning',11,T('First light','La primera luz'),T('Wake up somewhere<br><em>worth waking up for.</em>','Despierta donde<br><em>quieres estar.</em>'),T('Coffee on the balcony. A quiet ocean. Let the day begin when you’re ready.','Café en el balcón. El mar en calma. Que el día empiece cuando tú quieras.')),('afternoon',27,T('Long afternoons','Tardes sin prisa'),T('Stay for lunch.<br><em>Stay a little longer.</em>','Quédate a almorzar.<br><em>Quédate un rato más.</em>'),T('A shaded terrace, a table for your people and the pool just a few steps away.','Una terraza a la sombra, una mesa para los tuyos y la piscina a unos pasos.')),('evening',31,T('After sunset','Después del atardecer'),T('Nowhere else<br><em>you need to be.</em>','Ningún otro lugar<br><em>donde estar.</em>'),T('The house lights up. The pool turns blue. Another evening, entirely your own.','La casa se ilumina. La piscina se vuelve azul. Otra noche, solo para ustedes.'))]
    s=f'<section class="day-story section"><div class="day-heading"><span class="eyebrow">{T("A DAY AT WHITE SWAN","UN DÍA EN WHITE SWAN")}</span><p>{T("No itinerary required.","Sin itinerario.")}</p></div><div class="day-tabs" role="tablist" aria-label="{T("Imagine your day","Imagina tu día")}">'
    for i,(key,_,label,*rest) in enumerate(moments):
        active=key=='afternoon'
        s+=f'<button role="tab" id="day-tab-{key}" aria-controls="day-panel-{key}" aria-selected="{str(active).lower()}" tabindex="{0 if active else -1}" data-day-tab="{key}"><span>0{i+1}</span>{label}</button>'
    s+='</div>'
    for key,index,label,title,copy in moments:
        s+=f'<div class="day-panel" id="day-panel-{key}" role="tabpanel" aria-labelledby="day-tab-{key}" tabindex="0" {"hidden" if key!="afternoon" else ""}><figure>{photo(index,lang,sizes="(max-width: 700px) 100vw, 65vw")}<figcaption>{label} / WHITE SWAN</figcaption></figure><div><span class="day-sun" aria-hidden="true">✳</span><h2>{title}</h2><p>{copy}</p></div></div>'
    return s+'</section>'

def gallery(lang,head,components):
    T=lambda en,es:es if lang=='es' else en
    path='/es/fotos/' if lang=='es' else '/photos/';other='/photos/' if lang=='es' else '/es/fotos/'
    s=head(lang,path,T('A look around | White Swan Villa photo tour','Cada rincón | Recorrido fotográfico de White Swan'),T('Explore 36 photographs of White Swan Villa: bedrooms, open living, private infinity pool and the coast of Xanadu.','Explora 36 fotografías de White Swan: habitaciones, sala abierta, piscina infinita privada y la costa de Xanadu.'),other,'gallery')
    s+=f'<body class="editorial gallery-page" id="top">{navigation(lang,"photos")}<main id="main" class="section photo-tour"><span class="eyebrow">WHITE SWAN / {T("A CLOSER LOOK","DE CERCA")}</span><h1>{T("Picture yourself <em>here.</em>","Imagínate <em>aquí.</em>")}</h1><p class="muted">{T("The spaces, the little details, and that Pacific light.","Los espacios, los pequeños detalles y esa luz del Pacífico.")}</p><div class="gallery-filters" role="group" aria-label="{T("Filter photos","Filtrar fotos")}">'
    for key,en,es in [('all','All spaces','Todos los espacios'),('outdoors','Outdoors & pool','Exterior y piscina'),('bedrooms','Bedrooms','Habitaciones'),('living','Living & kitchen','Sala y cocina'),('details','The details','Los detalles')]:
        s+=f'<button data-photo-filter="{key}" aria-pressed="{str(key=="all").lower()}">{T(en,es)}</button>'
    s+=f'</div><p class="photo-results" role="status" aria-live="polite">36 {T("photos","fotos")}</p><div class="photo-tour-grid">'
    order=[28,29,32,9,30,27,31,35,8,10,11,12,13,14,15,16,17,18,1,7,2,0,3,4,5,6,24,25,26,19,20,21,22,23,33,34]
    for i in order:
        p=PHOTOS[i]
        s+=f'<figure data-photo-category="{p["category"]}"><a href="/assets/listing/{p["id"]}-1920.webp" data-photo-open data-caption="{escape(p["alt"][lang])}">{photo(i,lang,sizes="(max-width: 700px) 100vw, 33vw")}<span class="photo-open" aria-hidden="true">↗</span></a><figcaption>{escape(p["alt"][lang])}</figcaption></figure>'
    s+=f'''</div><noscript><p>{T('Select any photograph to open the full-size image.','Selecciona una fotografía para verla en tamaño completo.')}</p></noscript></main>{footer(lang)}{concierge_widget(lang,path)}<dialog class="photo-viewer" aria-label="{T('Photo viewer','Visor de fotografías')}"><div class="viewer-top"><span>WHITE SWAN</span><button data-viewer-close aria-label="{T('Close photo','Cerrar fotografía')}">×</button></div><div class="viewer-stage"><button data-photo-prev aria-label="{T('Previous photo','Foto anterior')}">←</button><img alt="" width="1600" height="1200"><button data-photo-next aria-label="{T('Next photo','Siguiente foto')}">→</button></div><div class="viewer-caption" aria-live="polite"><p></p><span></span></div></dialog>{components(lang)}</body></html>'''
    return s

def guest_reviews(lang):
    T=lambda en,es:es if lang=='es' else en
    data=json.loads((ROOT/'content/guest-reviews.json').read_text())
    months={'en':['January','February','March','April','May','June','July','August','September','October','November','December'],'es':['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']}
    s=f'''<section class="section guest-stories" id="guest-stories" aria-labelledby="reviews-heading"><div class="section-heading"><div><span class="eyebrow">{T('IN OUR GUESTS’ WORDS','EN PALABRAS DE NUESTROS HUÉSPEDES')}</span><h2 id="reviews-heading">{T('The memories<br><em>they took home.</em>','Los recuerdos<br><em>que se llevaron.</em>')}</h2></div><div><p>{T('A few favourite notes from guests who made White Swan their own.','Algunas de nuestras reseñas favoritas de quienes hicieron de White Swan su hogar.')}</p><a class="text-link" href="{data['source_url']}" target="_blank" rel="noopener">{T('Read reviews on Airbnb','Lee las reseñas en Airbnb')} ↗</a></div></div><div class="guest-review-grid">'''
    for r in data['reviews'][lang]:
        year,month,_=r['date'].split('-');date=months[lang][int(month)-1]+' '+year
        s+=f'''<figure class="guest-review"><div class="review-stars" aria-label="{T('5 out of 5 stars','5 de 5 estrellas')}"><span aria-hidden="true">★★★★★</span><span>5 / 5</span></div><blockquote><p lang="{lang}">“{escape(r['text'])}”</p></blockquote><figcaption><span>{T('Airbnb guest','Huésped de Airbnb')}</span><time datetime="{r['date']}">{date}</time></figcaption></figure>'''
    from datetime import date
    refreshed=date.fromisoformat(data['retrieved_at'])
    stamp=f"{refreshed.day} {months[lang][refreshed.month-1]} {refreshed.year}"
    return s+f'''</div><p class="fine review-source">{T('Selected five-star reviews · Original guest wording · Retrieved through Hospitable on','Selección de reseñas de cinco estrellas · Texto original de los huéspedes · Consultadas mediante Hospitable el')} {stamp}.</p></section>'''

def stay(lang,head,components):
    T=lambda en,es:es if lang=='es' else en
    target=booking_path(lang); other=booking_path('en' if lang=='es' else 'es')
    # Only use the exact property-specific embed exported by Hospitable after Direct setup.
    import re
    widget=(ROOT/'content/hospitable-widget.html.template').read_text()
    widget=re.sub(r'<!--.*?-->','',widget,flags=re.S).strip()
    s=head(lang,target,T('Plan your stay | White Swan Villa','Planea tu estadía | White Swan'),T('Plan your private villa escape at White Swan in Xanadu, El Salvador. Choose your dates and speak with your host.','Planea tu escapada a White Swan en Xanadu, El Salvador. Elige tus fechas y habla con tu anfitrión.'),other,'stay')
    s+=f'''<body class="editorial stay-page" id="top">{navigation(lang,'stay')}<main id="main"><section class="section stay-intro"><div><span class="eyebrow">{T('YOUR TIME AT WHITE SWAN','TU TIEMPO EN WHITE SWAN')}</span><h1>{T('A place for<br><em>your next chapter.</em>','Un lugar para<br><em>tu próxima historia.</em>')}</h1><p>{T('The whole villa. Your favourite people. Let’s find the right days for you.','Toda la villa. Tus personas favoritas. Busquemos los días perfectos para ustedes.')}</p></div><div class="stay-photo">{photo(29,lang,True)}<span>{T('Four bedrooms · Private infinity pool','Cuatro habitaciones · Piscina infinita privada')}</span></div></section><section class="section stay-booking" id="booking"><div class="stay-aside"><span class="eyebrow">{T('A STAY, MADE PERSONAL','UNA ESTADÍA A TU MEDIDA')}</span><h2>{T('Begin with<br><em>a few days away.</em>','Empieza con<br><em>unos días de descanso.</em>')}</h2><p>{T('From a quiet weekend to a long-awaited reunion, we’ll help you plan the details.','Desde un fin de semana tranquilo hasta un reencuentro esperado, te ayudamos con los detalles.')}</p><dl><div><dt>{T('Your space','Tu espacio')}</dt><dd>{T('Entire private villa','Villa privada completa')}</dd></div><div><dt>{T('The setting','El entorno')}</dt><dd>Xanadu · El Salvador</dd></div><div><dt>{T('Something extra','Un toque especial')}</dt><dd>{T('Chef, massage & more, on request','Chef, masajes y más, por solicitud')}</dd></div></dl></div><div class="booking-card">'''
    if widget:
        s+=f'''<span class="eyebrow">{T('RESERVE YOUR STAY','RESERVA TU ESTADÍA')}</span><h2>{T('Find your dates.','Elige tus fechas.')}</h2><div class="hospitable-widget" data-booking-provider="hospitable">{widget}</div><p class="fine">{T('Your booking follows the price, payment terms and cancellation policy shown in the booking flow.','Tu reserva se rige por el precio, las condiciones de pago y la política de cancelación indicados al reservar.')}</p><a class="text-link" href="https://wa.me/50370528003" target="_blank" rel="noopener">{T('Need help? Talk to your host','¿Necesitas ayuda? Habla con tu anfitrión')} ↗</a>'''
    else:
        s+=f'''<span class="eyebrow">{T('PLAN WITH YOUR HOST','PLANEA CON TU ANFITRIÓN')}</span><h2>{T('When would you<br><em>like to escape?</em>','¿Cuándo te gustaría<br><em>escaparte?</em>')}</h2><p class="booking-mode-note">{T('Online booking is being connected. For now, choose your preferred dates here and send your request to our host on WhatsApp.','Estamos conectando las reservas en línea. Por ahora, elige tus fechas aquí y envía tu solicitud al anfitrión por WhatsApp.')}</p><form id="stay-request" hidden><div class="booking-fields"><label>{T('Arrival','Llegada')}<input type="date" name="arrival" required></label><label>{T('Departure','Salida')}<input type="date" name="departure" required></label><label class="guest-field">{T('Guests','Huéspedes')}<select name="guests">{''.join(f'<option value="{i}">{i} '+T('guest' if i==1 else 'guests','huésped' if i==1 else 'huéspedes')+'</option>' for i in range(1,9))}<option value="larger">{T('Larger group — ask us','Grupo más grande — consultar')}</option></select></label></div><p class="fine">{T('We confirm the permitted group size with your dates. No availability or price is confirmed by this form.','Confirmamos el tamaño permitido del grupo junto con tus fechas. Este formulario no confirma disponibilidad ni precio.')}</p><p id="stay-error" class="form-status" role="alert"></p><button type="submit" class="button">{T('Prepare my stay request','Preparar mi solicitud')} →</button></form><noscript><p>{T('Contact your host with your dates and group size.','Contacta al anfitrión con tus fechas y el tamaño del grupo.')}</p><a class="button" href="https://wa.me/50370528003" target="_blank" rel="noopener">WhatsApp ↗</a></noscript><div id="stay-summary" hidden aria-labelledby="stay-summary-title" tabindex="-1"><h3 id="stay-summary-title">{T('Your stay, at a glance.','Tu estadía, en un vistazo.')}</h3><p class="stay-selection"></p><p>{T('Your request is ready to send. Nothing has been sent or reserved yet. Your host will confirm availability, the full price and booking terms.','Tu solicitud está lista para enviar. Aún no se ha enviado ni reservado nada. Tu anfitrión confirmará disponibilidad, precio total y condiciones.')}</p><a class="button stay-whatsapp" target="_blank" rel="noopener">{T('Send request on WhatsApp','Enviar solicitud por WhatsApp')} ↗</a><button class="text-link" type="button" id="edit-stay">{T('Change my dates','Cambiar mis fechas')}</button></div><p class="fine booking-footnote">{T('No payment is taken here. Your stay is confirmed only after the host accepts your booking and you meet the agreed payment terms.','Aquí no se cobra ningún pago. Tu estadía se confirma cuando el anfitrión acepta la reserva y cumples las condiciones de pago acordadas.')}</p>'''
    s+=f'''</div></section><div class="section stay-help"><p>{T('A question before you decide?','¿Una pregunta antes de decidir?')}</p><a class="text-link" href="https://wa.me/50370528003" target="_blank" rel="noopener">{T('Speak with your host','Habla con tu anfitrión')} ↗</a><a class="text-link" href="{AIRBNB}" target="_blank" rel="noopener">{T('Prefer Airbnb? View our listing','¿Prefieres Airbnb? Ver el anuncio')} ↗</a></div></main>{footer(lang,'stay')}{concierge_widget(lang,target)}{components(lang)}<script src="/assets/booking.js" defer></script></body></html>'''
    return s
